name: Pipeline 

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 app.py
        pylint app.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
